Added doit script to update ui with current tests from rust submodule.
Trimmed Makefile and removed erroring tests when attempting to compile.

diff --git a/doit b/doit
--- a/doit
+++ b/doit
@@ -1,3 +1,21 @@
 #! /bin/bash
 
+# Update rust submodule with current tests
 git submodule update --remote --recursive;
+
+# Update ui with updated tests from submodule
+rust_tests_dir="rust/tests/";
+
+for file_path in $(find ui -name '*.rs'); 
+do 
+    # Attempt to copy test over 
+    rust_test="$rust_tests_dir$file_path"
+    cp $rust_test $file_path
+    
+    # If copying failed, delete the test
+    return=$(echo $?)
+    if [ 0 -lt $return ]
+    then
+        rm "$file_path"
+    fi
+done
